title: "Mert Satilmaz Tech Blog"
description: Security engineering, cloud guardrails, vulnerability management at scale
theme: minima
markdown: kramdown

github_username: mertsatilmaz
linkedin_username: mertsatilmaz
